# Generated by Django 4.1.3 on 2024-06-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="include_in_cards1_section",
            field=models.BooleanField(default=False),
        ),
    ]
