# Generated by Django 4.1.3 on 2024-06-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_productcategory_include_in_cards1_section"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="productcategory",
            name="include_in_cards1_section",
        ),
    ]
