# Generated by Django 4.1.3 on 2024-06-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_specialcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="special_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="store.specialcategory",
            ),
        ),
    ]
