# Generated by Django 4.1.3 on 2024-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="session_key",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
